general:
  buildTool: maven

steps:
  mavenExecute:
    goals:
      - compile
      - test-compile
      - package
    m2Path: .m2

  mavenTest:
    goals:
      - test
    m2Path: .m2

  mavenCoverage:
    goals:
      - jacoco:report
    m2Path: .m2
