general:
  buildTool: maven

steps:
  mavenExecute:
    goals:
      - compile
      - test-compile
      - package
#    defines:
#      - "-Dmaven.repo.local=/home/runner/.m2/repository"
  mavenTest:
    goals:
      - test
  mavenCoverage:
    goals:
      - jacoco:report