name: Java CI with Maven

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-test-coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      - name: Create Writable Maven Repo
        run: |
          mkdir -p target
          chmod -R 777 .
          mkdir -p .m2/repository
          chmod -R 777 .m2
      - name: Run Piper Maven Build
        uses: SAP/project-piper-action@v1.26.2
        with:
          step-name: mavenExecute
          flags: --goals clean,compile,test-compile,package
        env:
          HOME: ${{ github.workspace }}
          PIPER_CONFIG_FILE: ".pipeline/config.yml"

      - name: Run Tests
        uses: SAP/project-piper-action@v1.26.2
        with:
          step-name: mavenTest
          flags: --goals test
        env:
          HOME: ${{ github.workspace }}

      - name: Generate Coverage
        uses: SAP/project-piper-action@v1.26.2
        with:
          step-name: mavenCoverage
          flags: --goals jacoco:report
        env:
          HOME: ${{ github.workspace }}
