name: CI Pipeline

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Create Maven Repository Directory
        run: |
          mkdir -p $HOME/.m2/repository
          chmod -R 755 $HOME/.m2

      - name: Run Piper Maven Build
        uses: SAP/project-piper-action@v1.26.2
        with:
          step-name: mavenExecute
        env:
          HOME: /home/runner

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: gha-demo-jar
          path: target/*.jar